name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-26
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Test 0
        run: |
          cd $GITHUB_WORKSPACE/Tests/T0-Basic
          cmake -B Build
          cmake --build Build
          ./Build/T00
